### ISSUE TITLE
Date format for localization

### ISSUE THREAD

**Issue by menakas** [presscustomizr/hueman#225] opened 2016-04-21 04:42 UTC
Question on the site (disqus forums) from a customer:

Shouldn't end of line 17 in single-author-date.php say
the_modified_time(get_option('date_format'));
rather than:
the_modified_time('F j, Y');
for localization, etc.?

**Comment by Nikeo** [comment] 2016-04-22 06:59
Yes. The problem is that it's been like that since the beginning to the theme and many users might see a different date format displayed if their date_format option is not 'F j, Y'

**Comment by dhm80** [comment] 2016-05-03 11:59
@menakas I just came accross the same problem: It just doesn't look right with the different date formats.

@Nikeo Even if it was "wrong" since the beginning of the theme it's still a bug to me. So why not correct it?

**Comment by Nikeo** [comment] 2016-05-03 13:37
@dhm80 I agree 100%. This will be fixed

**Closed** 2019-11-28 14:22 UTC
Labels: Triage-2019, question, urgent
